# Generated by Django 5.2.7 on 2025-10-02 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Event name (e.g., 'User Registration')", max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe event identifier', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Description of when this event occurs')),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_method', models.CharField(choices=[('api', 'API Call'), ('manual', 'Manual Trigger'), ('scheduled', 'Scheduled'), ('internal', 'Internal System Event')], default='api', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Email template to use for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='templates_manager.emailtemplate')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('event_data', models.JSONField(help_text='JSON data passed with the event')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='events.eventtype')),
            ],
            options={
                'verbose_name': 'Event Trigger',
                'verbose_name_plural': 'Event Triggers',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, help_text='Default value if not provided', max_length=255)),
                ('placeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_manager.placeholder')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='events.eventtype')),
            ],
            options={
                'verbose_name': 'Event Placeholder',
                'verbose_name_plural': 'Event Placeholders',
                'unique_together': {('event_type', 'placeholder')},
            },
        ),
    ]
