# Generated by Django 5.2.7 on 2025-10-02 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Placeholder name (without braces)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of what this placeholder represents')),
                ('example_value', models.CharField(blank=True, help_text='Example value for preview', max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('email', 'Email'), ('url', 'URL')], default='string', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placeholder',
                'verbose_name_plural': 'Placeholders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique template name', max_length=255, unique=True)),
                ('subject', models.CharField(help_text='Email subject (supports {{placeholders}})', max_length=500)),
                ('body_html', models.TextField(help_text='HTML email body (supports {{placeholders}})')),
                ('body_plain', models.TextField(blank=True, help_text='Plain text email body (optional)')),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, help_text='Previous version of this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='templates_manager.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='template_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='templates_manager.emailtemplate')),
            ],
            options={
                'verbose_name': 'Template Attachment',
                'verbose_name_plural': 'Template Attachments',
            },
        ),
    ]
